[package]
name = "soltrade"
version = "0.1.0"
description = "a peer to peer trading system on Solana"
edition = "2021"

[lib]
crate-type = ["cdylib", "lib"]
name = "soltrade"

[features]
no-entrypoint = []
no-idl = []
no-log-ix-name = []
cpi = ["no-entrypoint"]
default = []

[dependencies]
anchor-lang = "0.28.0"
anchor-spl = "0.28.0"
solana-safe-math = "0.1.0"
wasm-bindgen-macro = "=0.2.95"
serde_derive = "1.0.215"
serde = "1.0.215"
solana-program = "=1.16.6"

[dev-dependencies]
toml_datetime = "=0.6.3"
winnow = "=0.5.3"
