[toolchain]
anchor_version = "0.28.0"

[features]
resolution = true
skip-lint = false

[programs.localnet]
soltrade = "AHwXuw8go83wWKF8PSXeMAzfaPhxF5t3GH7n4jQRPpJW"

[programs.devnet]
soltrade = "AHwXuw8go83wWKF8PSXeMAzfaPhxF5t3GH7n4jQRPpJW"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"                   # Localnet / devnet
wallet = "~/.config/solana/dev.json"

[scripts]
# test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
test = "bun run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
# test = "yarn run test"
# test = "bun test -t 1000000"
